version: '3.2'
services:

  event-postgres:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc-event-postgres:${tag}
    build:
      context: .
      dockerfile: Dockerfile-postgres

  event:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc-event:${tag}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - event-postgres
    ports:
    - "8081:80"
